apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: ClusterSecretStore
  target:
    name: app-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: 'rds!db-91179694-172f-49a2-9fea-679915e75cd1'
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: 'rds!db-91179694-172f-49a2-9fea-679915e75cd1'
        property: password