apiVersion: v1
kind: PersistentVolume

metadata:
  name: s3-pv

spec:
  capacity:
    storage: 1200Gi

  accessModes:
    - ReadWriteMany

  persistentVolumeReclaimPolicy: Retain

  storageClassName: s3-sc

  mountOptions:
    - allow-delete
    - region ap-southeast-1

  csi:
    driver: s3.csi.aws.com

    volumeHandle: tharun-nginx-s3-demo

    volumeAttributes:
      bucketName: tharun-nginx-s3-demo
