apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-test-secret
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "arn:aws:secretsmanager:ap-southeast-1:783764580882:secret:rds!db-91179694-172f-49a2-9fea-679915e75cd1-8p8qkK"
        objectType: "secretsmanager"
        jmesPath:
          - path: "username"
            objectAlias: "DB_USERNAME"
          - path: "password"
            objectAlias: "DB_PASSWORD"

      - objectName: "/prod/app/APP_ENV"
        objectType: "ssmparameter"
        objectAlias: "APP_ENV"

      - objectName: "/prod/app/LOG_LEVEL"
        objectType: "ssmparameter"
        objectAlias: "LOG_LEVEL"